root = "."
tmp_dir = "tmp"

[build]
cmd = "go version"
entrypoint = ["go", "run", "./cmd/server/main.go"]
include_ext = ["go", "env"]
exclude_dir = ["tmp"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[misc]
clean_on_exit = true