[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:server]
command=/app/zonelease-backend
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/server.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/app/logs/server.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[program:frontend]
command=node .output/server/index.mjs
directory=/app/frontend
environment=HOST="127.0.0.1",PORT="5173"
autostart=true
autorestart=true
stdout_logfile=/app/logs/frontend.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/app/logs/frontend.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
